CREATE TABLE IF NOT EXISTS country (
    countryID  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(50)
);

CREATE TABLE IF NOT EXISTS company (
    companyID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    size      char(1),
    countryID int,
    FOREIGN KEY (countryID) REFERENCES country(countryID)
);

CREATE TABLE IF NOT EXISTS employee (
    employeeID     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year           int,
    employment_type char(2),
    job_title      varchar(50),
    salary         int,
    currency       char(3),
    salary_usd     int,
    remote_ratio   int,
    countryID      int,
    companyID      int,
    FOREIGN KEY (countryID) REFERENCES country(countryID),
    FOREIGN KEY (companyID) REFERENCES company(companyID)
);

CREATE TABLE IF NOT EXISTS log (
    logID      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description text,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS invalid_input (
    invalidID     SERIAL PRIMARY KEY,
    target_table  varchar(50),
    field_name    varchar(100),
    raw_value     text,
    full_record   jsonb,
    error_message text NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION trg_log_employee_insert()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO log (description)
  VALUES (
    format(
      'Inserted employeeID=%s, job_title=%s, salary=%s, countryID=%s, companyID=%s',
      NEW.employeeID,
      NEW.job_title,
      NEW.salary,
      NEW.countryID,
      NEW.companyID
    )
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE TRIGGER log_employee_insert
AFTER INSERT ON employee
FOR EACH ROW
EXECUTE FUNCTION trg_log_employee_insert();

---------------------------------

CREATE OR REPLACE FUNCTION trg_validate_employee_insert()
RETURNS TRIGGER AS $$
DECLARE
  error_msg text := '';
BEGIN

-- Validations

-- Year
  IF length(NEW.year::text) != 4 THEN
    error_msg := error_msg || 'year must be exactly 4 digits; ';
  END IF;

-- Employment Type
  IF length(trim(NEW.employment_type)) != 2 THEN
    error_msg := error_msg || 'employment type must be exactly 2 characters; ';
  END IF;

-- Job Title
  IF length(NEW.job_title) = 0 THEN 
    error_msg := error_msg || 'job title cannot be empty; ';
  ELSIF length(NEW.job_title) > 50 THEN 
    error_msg := error_msg || 'job title must be at most 50 characters; ';
  END IF;

-- Salary
  IF NEW.salary IS NULL OR NEW.salary <= 0 THEN
    error_msg := error_msg || 'salary must be positive; ';
  END IF;

-- Currency
  IF length(NEW.currency) = 0 THEN 
    error_msg := error_msg || 'currency cannot be empty; ';
  ELSIF length(NEW.currency) > 3 THEN 
    error_msg := error_msg || 'currency must be at most 3 characters; ';
  END IF;

  -- If any error detected, log to invalid_input and stop the insert
  IF error_msg <> '' THEN
    INSERT INTO invalid_input (
      target_table,
      field_name,
      raw_value,
      full_record,
      error_message
    )
    VALUES (
      'employee',
      NULL,
      NULL,
      to_jsonb(NEW),
      trim(both ' ' from error_msg)
    );

    -- Return NULL to prevent the insert instead of raising exception
    RETURN NULL;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER validate_employee_insert
BEFORE INSERT ON employee
FOR EACH ROW
EXECUTE FUNCTION trg_validate_employee_insert();

--TRUNCATE TABLE employee, country, company RESTART IDENTITY